// Arabic Alphabet and Vocabulary for Learning

export interface Letter {
  id: string;
  ar: string;
  name: string;
  english: string;
  isolated: string;
  initial: string;
  medial: string;
  final: string;
  audioUrl: string;
}

export interface Word {
  id: string;
  ar: string;
  en: string;
  imageUrl: string;
  audioUrl: string;
  category: string;
}

// Arabic Alphabet (28 letters)
export const arabicAlphabet: Letter[] = [
  {
    id: 'alif',
    ar: 'ا',
    name: 'Alif',
    english: 'A',
    isolated: 'ا',
    initial: 'ا',
    medial: 'ا',
    final: 'ا',
    audioUrl: '/audio/alif.mp3',
  },
  {
    id: 'ba',
    ar: 'ب',
    name: 'Ba',
    english: 'B',
    isolated: 'ب',
    initial: 'بـ',
    medial: 'ـبـ',
    final: 'ـب',
    audioUrl: '/audio/ba.mp3',
  },
  {
    id: 'ta',
    ar: 'ت',
    name: 'Ta',
    english: 'T',
    isolated: 'ت',
    initial: 'تـ',
    medial: 'ـتـ',
    final: 'ـت',
    audioUrl: '/audio/ta.mp3',
  },
  {
    id: 'tha',
    ar: 'ث',
    name: 'Tha',
    english: 'Th',
    isolated: 'ث',
    initial: 'ثـ',
    medial: 'ـثـ',
    final: 'ـث',
    audioUrl: '/audio/tha.mp3',
  },
  {
    id: 'jim',
    ar: 'ج',
    name: 'Jim',
    english: 'J',
    isolated: 'ج',
    initial: 'جـ',
    medial: 'ـجـ',
    final: 'ـج',
    audioUrl: '/audio/jim.mp3',
  },
  {
    id: 'ha',
    ar: 'ح',
    name: 'Ha',
    english: 'H',
    isolated: 'ح',
    initial: 'حـ',
    medial: 'ـحـ',
    final: 'ـح',
    audioUrl: '/audio/ha.mp3',
  },
  {
    id: 'kha',
    ar: 'خ',
    name: 'Kha',
    english: 'Kh',
    isolated: 'خ',
    initial: 'خـ',
    medial: 'ـخـ',
    final: 'ـخ',
    audioUrl: '/audio/kha.mp3',
  },
  {
    id: 'dal',
    ar: 'د',
    name: 'Dal',
    english: 'D',
    isolated: 'د',
    initial: 'د',
    medial: 'د',
    final: 'ـد',
    audioUrl: '/audio/dal.mp3',
  },
  {
    id: 'thal',
    ar: 'ذ',
    name: 'Thal',
    english: 'Dh',
    isolated: 'ذ',
    initial: 'ذ',
    medial: 'ذ',
    final: 'ـذ',
    audioUrl: '/audio/thal.mp3',
  },
  {
    id: 'ra',
    ar: 'ر',
    name: 'Ra',
    english: 'R',
    isolated: 'ر',
    initial: 'ر',
    medial: 'ر',
    final: 'ـر',
    audioUrl: '/audio/ra.mp3',
  },
  {
    id: 'za',
    ar: 'ز',
    name: 'Za',
    english: 'Z',
    isolated: 'ز',
    initial: 'ز',
    medial: 'ز',
    final: 'ـز',
    audioUrl: '/audio/za.mp3',
  },
  {
    id: 'sin',
    ar: 'س',
    name: 'Sin',
    english: 'S',
    isolated: 'س',
    initial: 'سـ',
    medial: 'ـسـ',
    final: 'ـس',
    audioUrl: '/audio/sin.mp3',
  },
  {
    id: 'shin',
    ar: 'ش',
    name: 'Shin',
    english: 'Sh',
    isolated: 'ش',
    initial: 'شـ',
    medial: 'ـشـ',
    final: 'ـش',
    audioUrl: '/audio/shin.mp3',
  },
  {
    id: 'sad',
    ar: 'ص',
    name: 'Sad',
    english: 'S',
    isolated: 'ص',
    initial: 'صـ',
    medial: 'ـصـ',
    final: 'ـص',
    audioUrl: '/audio/sad.mp3',
  },
  {
    id: 'dad',
    ar: 'ض',
    name: 'Dad',
    english: 'D',
    isolated: 'ض',
    initial: 'ضـ',
    medial: 'ـضـ',
    final: 'ـض',
    audioUrl: '/audio/dad.mp3',
  },
  {
    id: 'tah',
    ar: 'ط',
    name: 'Tah',
    english: 'T',
    isolated: 'ط',
    initial: 'طـ',
    medial: 'ـطـ',
    final: 'ـط',
    audioUrl: '/audio/tah.mp3',
  },
  {
    id: 'zah',
    ar: 'ظ',
    name: 'Zah',
    english: 'Z',
    isolated: 'ظ',
    initial: 'ظـ',
    medial: 'ـظـ',
    final: 'ـظ',
    audioUrl: '/audio/zah.mp3',
  },
  {
    id: 'ain',
    ar: 'ع',
    name: 'Ain',
    english: 'A',
    isolated: 'ع',
    initial: 'عـ',
    medial: 'ـعـ',
    final: 'ـع',
    audioUrl: '/audio/ain.mp3',
  },
  {
    id: 'ghain',
    ar: 'غ',
    name: 'Ghain',
    english: 'Gh',
    isolated: 'غ',
    initial: 'غـ',
    medial: 'ـغـ',
    final: 'ـغ',
    audioUrl: '/audio/ghain.mp3',
  },
  {
    id: 'fa',
    ar: 'ف',
    name: 'Fa',
    english: 'F',
    isolated: 'ف',
    initial: 'فـ',
    medial: 'ـفـ',
    final: 'ـف',
    audioUrl: '/audio/fa.mp3',
  },
  {
    id: 'qaf',
    ar: 'ق',
    name: 'Qaf',
    english: 'Q',
    isolated: 'ق',
    initial: 'قـ',
    medial: 'ـقـ',
    final: 'ـق',
    audioUrl: '/audio/qaf.mp3',
  },
  {
    id: 'kaf',
    ar: 'ك',
    name: 'Kaf',
    english: 'K',
    isolated: 'ك',
    initial: 'كـ',
    medial: 'ـكـ',
    final: 'ـك',
    audioUrl: '/audio/kaf.mp3',
  },
  {
    id: 'lam',
    ar: 'ل',
    name: 'Lam',
    english: 'L',
    isolated: 'ل',
    initial: 'لـ',
    medial: 'ـلـ',
    final: 'ـل',
    audioUrl: '/audio/lam.mp3',
  },
  {
    id: 'meem',
    ar: 'م',
    name: 'Meem',
    english: 'M',
    isolated: 'م',
    initial: 'مـ',
    medial: 'ـمـ',
    final: 'ـم',
    audioUrl: '/audio/meem.mp3',
  },
  {
    id: 'noon',
    ar: 'ن',
    name: 'Noon',
    english: 'N',
    isolated: 'ن',
    initial: 'نـ',
    medial: 'ـنـ',
    final: 'ـن',
    audioUrl: '/audio/noon.mp3',
  },
  {
    id: 'ha_final',
    ar: 'ه',
    name: 'Ha',
    english: 'H',
    isolated: 'ه',
    initial: 'هـ',
    medial: 'ـهـ',
    final: 'ـه',
    audioUrl: '/audio/ha_final.mp3',
  },
  {
    id: 'waw',
    ar: 'و',
    name: 'Waw',
    english: 'W',
    isolated: 'و',
    initial: 'و',
    medial: 'و',
    final: 'ـو',
    audioUrl: '/audio/waw.mp3',
  },
  {
    id: 'ya',
    ar: 'ي',
    name: 'Ya',
    english: 'Y',
    isolated: 'ي',
    initial: 'يـ',
    medial: 'ـيـ',
    final: 'ـي',
    audioUrl: '/audio/ya.mp3',
  },
];

// Basic Vocabulary - Level 3 (Family, Numbers, Colors)
export const basicVocabulary: Word[] = [
  // Family
  { id: 'ab', ar: 'أب', en: 'Father', imageUrl: '/images/father.jpg', audioUrl: '/audio/word-ab.mp3', category: 'family' },
  { id: 'um', ar: 'أم', en: 'Mother', imageUrl: '/images/mother.jpg', audioUrl: '/audio/word-um.mp3', category: 'family' },
  { id: 'akh', ar: 'أخ', en: 'Brother', imageUrl: '/images/brother.jpg', audioUrl: '/audio/word-akh.mp3', category: 'family' },
  { id: 'ukht', ar: 'أخت', en: 'Sister', imageUrl: '/images/sister.jpg', audioUrl: '/audio/word-ukht.mp3', category: 'family' },

  // Numbers
  { id: 'wahid', ar: 'واحد', en: 'One', imageUrl: '/images/one.jpg', audioUrl: '/audio/word-wahid.mp3', category: 'numbers' },
  { id: 'ithnain', ar: 'اثنان', en: 'Two', imageUrl: '/images/two.jpg', audioUrl: '/audio/word-ithnain.mp3', category: 'numbers' },
  { id: 'talata', ar: 'ثلاثة', en: 'Three', imageUrl: '/images/three.jpg', audioUrl: '/audio/word-talata.mp3', category: 'numbers' },
  { id: 'arbaa', ar: 'أربعة', en: 'Four', imageUrl: '/images/four.jpg', audioUrl: '/audio/word-arbaa.mp3', category: 'numbers' },
  { id: 'khamsa', ar: 'خمسة', en: 'Five', imageUrl: '/images/five.jpg', audioUrl: '/audio/word-khamsa.mp3', category: 'numbers' },

  // Colors
  { id: 'ahmar', ar: 'أحمر', en: 'Red', imageUrl: '/images/red.jpg', audioUrl: '/audio/word-ahmar.mp3', category: 'colors' },
  { id: 'azraq', ar: 'أزرق', en: 'Blue', imageUrl: '/images/blue.jpg', audioUrl: '/audio/word-azraq.mp3', category: 'colors' },
  { id: 'aswad', ar: 'أسود', en: 'Black', imageUrl: '/images/black.jpg', audioUrl: '/audio/word-aswad.mp3', category: 'colors' },
  { id: 'abyad', ar: 'أبيض', en: 'White', imageUrl: '/images/white.jpg', audioUrl: '/audio/word-abyad.mp3', category: 'colors' },
];

// Reading Level 4 - Simple Sentences
export const simpleSentences = [
  { ar: 'السلام عليكم', en: 'Hello (peace be upon you)', audioUrl: '/audio/sentence-salaam.mp3' },
  { ar: 'أنا اسمي محمد', en: 'My name is Mohammed', audioUrl: '/audio/sentence-name.mp3' },
  { ar: 'كم عمرك؟', en: 'How old are you?', audioUrl: '/audio/sentence-age.mp3' },
  { ar: 'أنا من مصر', en: 'I am from Egypt', audioUrl: '/audio/sentence-country.mp3' },
  { ar: 'أحب اللغة العربية', en: 'I love the Arabic language', audioUrl: '/audio/sentence-love.mp3' },
];
